[package]
name = "cairo-vm-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode = { version = "2.0.0-rc.2", tag = "v2.0.0-rc.2", git = "https://github.com/bincode-org/bincode.git" }
cairo-vm.workspace = true
clap = { version = "3.2.5", features = ["derive"] }
mimalloc = { version = "0.1.29", default-features = false, optional = true }
nom = "7"
thiserror = { version = "1.0.32" }

[features]
default = ["with_mimalloc"]
with_mimalloc = ["cairo-vm/with_mimalloc", "mimalloc"]
