name: Cairo 1 programs execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  run:
    name: Execute programs
    runs-on: ubuntu-24.04
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.85.0
      - name: Set up Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: install corelib
        run:  cd cairo1-run/ && make deps
      - name: Run tests
        run:  cd cairo1-run/ && make test
      - name: Run cairo 1 programs
        run:  cd cairo1-run/ && make run
