name: "Fuzzer Workflow"
on:
  schedule:
  # At the end of every day
  - cron: "* 0 * * *"    
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Inputs
      id: cache-inputs
      uses: actions/cache@v3
      with:
        path: test_fuzzer/hfuzz_workspace/input
        key: ${{ runner.os }}-inputs

    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install binutils-dev
        sudo apt-get install libunwind-dev
        sudo curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain nightly

    - name: Set Environment Variable
      run: echo "PATH="/root/.cargo/bin:${PATH}"" >> $GITHUB_ENV

    - name: Install Honggfuzz
      run: cargo install honggfuzz

    - if: ${{ steps.cache-inputs.outputs.cache-hit != 'true' }}
      name: Initializing fuzzer from 0 
      run: |
        cd test_fuzzer
        HFUZZ_RUN_ARGS="--run_time 60" cargo hfuzz run test_fuzzer

    - if: ${{ steps.cache-inputs.outputs.cache-hit != 'false' }}
      name: Initializing fuzzer with previous inputs 
      run: |
        cd test_fuzzer
        HFUZZ_RUN_ARGS="--run_time 60 --minimize" cargo hfuzz run test_fuzzer

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: changing report
        file_pattern: '*/hfuzz_workspace/test_fuzzer/HONGGFUZZ*  */hfuzz_workspace/test_fuzzer/SIG*'
