name: publish

on:
  push:
    tags:        
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@1.69.0
    - name: Publish crate cairo-take_until_unbalanced
      env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --token ${CRATES_TOKEN} --all-features --manifest-path ./deps/parse-hyperlinks/Cargo.toml
    - name: Publish crate cairo-felt
      env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --token ${CRATES_TOKEN} --all-features --manifest-path ./felt/Cargo.toml
    # FIXME: there should be a better way to make sure the index in crates.io is updated before publishing
    # cairo-vm but right now the step throws timeout and fails. 
    - name: wait for index in crates.io
      run: sleep 120
    - name: Publish crate cairo-vm
      env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --token ${CRATES_TOKEN} --all-features -p cairo-vm
