name: Test dependencies and cairo-vm install

on:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  install:
    name: "Install on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - if: matrix.os == 'ubuntu-22.04'
        name: "Install on ubuntu-22.04"
        run: install-scripts/install-ubuntu.sh

      - if: matrix.os == 'macos-12'
        name: "Install on macos-12"
        run: install-scripts/install-macos.sh

  install_debian:
    name: "Install on debian-11"
    runs-on: ubuntu-22.04
    container:
      image: debian:11

    steps:
      - uses: actions/checkout@v3

      - name: "Install on debian-11"
        run: install-scripts/install-debian.sh
